### ISSUE TITLE
Preview unavailable (sorry, we couldn't find this file in the repository)

### ISSUE THREAD

**Issue by Arkq** [psastras/sarif-rs#271]
I'm trying to add support for code scanning alerts to https://github.com/ludeeus/action-shellcheck (here is my fork: https://github.com/Arkq/action-shellcheck). I've integrated `shellcheck-sarif` (many thanks for this project) with the action runner, so right now I've got scanning alerts. However, it seems that the file path in the SARIF file is incorrect. When exploring alerts, there is no file preview. See screenshot below:

![image](https://user-images.githubusercontent.com/6979798/182044160-f4b67d9a-e676-4e22-a539-6b2194966b59.png)
 
On my other projects I'm using CodeQL checks, and I've noticed that the file path does not begin with "./" there. Maybe that's the issue?

![image](https://user-images.githubusercontent.com/6979798/182044213-b4a1603d-fe0d-422e-b7a4-bbfa892d67a8.png)

**Comment by psastras** [comment]
@Arkq basically `shellcheck-sarif` will output the file path in the same way the file path is input into the tool.

so if you run `shellcheck -f json shell.sh | shellcheck-sarif`, the output sarif file will contain path references to `shell.sh`

if you run `shellcheck -f json ./shell.sh | shellcheck-sarif`, the output sarif file will contain path references to `./shell.sh`

I think if possible, the best solution would be to see if you can adjust the way you invoke `shellcheck` to pass the file in without the `./`. If that's not possible, we'd need to discuss a way of rewriting paths and a common interface to that.

**Comment by Arkq** [comment]
> basically shellcheck-sarif will output the file path in the same way the file path is input into the tool.

OK, it seems reasonable. I've modified `shellcheck` run, so the leading `./` is removed. Not it works perfectly :)

**Comment by ImUrX** [comment]
I'm having the same issue with clippy and even though I specify the ``--manifest-path`` from another dir it doesn't work. What should I do?

**Comment by ImUrX** [comment]
I think I should do a different issue, this talks about ``shellcheck`` :laughing:
