### ISSUE TITLE
README suggests to download a very old version

### ISSUE THREAD

**Issue by TWiStErRob** [psastras/sarif-rs#407]
https://github.com/psastras/sarif-rs/releases/shellcheck-sarif-latest points to 0.2.26 which is more than a year old.

https://github.com/psastras/sarif-rs/blob/591b6e9fae691c2b3d01e01da6c29d90bf70cdbe/README.md#L46-L56

Probably the release process is missing a step to bump the stable tags.

**Comment by TWiStErRob** [comment]
Same at https://docs.rs/crate/shellcheck-sarif/latest

**Comment by psastras** [comment]
Thanks reporting. Will take a look.

**Comment by psastras** [comment]
These latest tags should be working properly now.
