### ISSUE TITLE
issue with handling of warning/error report level

### ISSUE THREAD

**Issue by igrr** [psastras/sarif-rs#409]
I've noticed what looks like an issue, but I'm not exactly sure if the issue is in clang-tidy-sarif or in sarif-fmt or in my understanding how they should be propertly used.

If I run the example from the test case, `clang-tidy '-checks=cert-*' cpp.cpp | clang-tidy-sarif`, in SARIF file I get 3 "results" with level: "warning" reported. If I then run that SARIF through `sarif-fmt` it prints 3 warnings. So far so good.

Now I tell clang-tidy to report one of the warnings as an error: `clang-tidy '-checks=cert-*' '-warnings-as-errors=clang*' cpp.cpp | clang-tidy-sarif`. This gets me two "results" in SARIF with level: "warning" and one result with level: "error". This looks reasonable. But if I run that SARIF through sarif-fmt, it still prints 3 warnings, not 2 warnings an 1 error.

I have read the [long explanation](https://github.com/psastras/sarif-rs/blob/fe270b7bbfc072b0cf2761f5e8e8dfa8ba1ecb5f/sarif-fmt/src/bin.rs#L306-L324) about `level` handling, and it seems to indicate that clang-tidy-sarif needs to also fill in `kind` and maybe `rules` fields, for sarif-fmt to show something as an `error`. Is my understanding correct? Or should this be fixed in some other way?

**Comment by psastras** [comment]
hmmm, reading through the specification again (https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541086) 

it seems the implementation in sarif-fmt is just flat out missing the first stanza:

> A result object MAY contain a property named level whose value is one of a fixed set of strings that specify the severity level of the result.
> 
> If present, the level property SHALL have one of the following values, with the specified meanings:
> 
> ·         "warning": The rule specified by ruleId was evaluated and a problem was found.
> 
> ·         "error": The rule specified by ruleId was evaluated and a serious problem was found.
> 
> ·         "note": The rule specified by ruleId was evaluated and a minor problem or an opportunity to improve the code was found.
> 
> ·         "none": The concept of “severity” does not apply to this result because the kind property (§3.27.9) has a value other than "fail".

I'm not sure why, since that seems like a very weird / obvious thing to skip. But seems like a bug.

**Comment by igrr** [comment]
Reading "3.27.9 kind property" section, looks like we should also set `kind: "fail"` for every result:

> A result object MAY contain a property named kind whose value is one of a fixed set of strings that specify the nature of the result.

> If present, the kind property SHALL have one of the following values, with the specified meanings:
> ...
> "fail": The result represents a problem whose severity is specified by the level property (§3.27.10).

**Comment by psastras** [comment]
hmm, ah yeah maybe I had it right the first time around, I think what's missing is the sentence immediately after:

> If kind is absent, it SHALL default to "fail".

It's also a bit late so maybe if I read with a fresh pair of eyes it'll be more clear what's going on, but that seems suspicious.
