### ISSUE TITLE
Add SARIF to (GitLab) Code Quality converter?

### ISSUE THREAD

**Issue by ahogen** [psastras/sarif-rs#456]
Hi there!

I used a bit of your SARIF parsing library to convert from SARIF to GitLab CodeQuality here: https://gitlab.com/ahogen/sarif-to-codequality

I'm new to Rust, so this was a somewhat simple way for me to learn some Rust concepts. Now that I'm done working on it, if you want to refactor and integrate it into this repo alongside your other converters, let me know!

Otherwise thanks for the useful library, and cheers!

**Comment by psastras** [comment]
hi, @ahogen happy to see you found the library useful. i'm open to including it with the other converters if you'd like.

there's no contribution guide unfortunately, but generally:

- be aware of the license (I'd like to maintain an MIT license on everything here); if this does not make sense for your code, it's probably better to keep it separate
- maintenance, etc. i can do some basic best effort support for any issues with your converter, but won't promise anything. i'm happy to give collaborator access to you to continue to maintain and help improve it
- style: stuff in this codebase generally follows a uniform style, and I'd like to maintain that as much as possible, so it may require some changes if you'd like to bring a new tool in

**Comment by ahogen** [comment]
In retrospect, I should probably get better at my rust-foo before contributing to a public project like yours so it may be best for me to keep my crufty code off on its own. That and I find myself focused on tasks at work with little time to code at home. 

Thanks for your time. Cheers!
