### ISSUE TITLE
Can serde_sarif be considered stable now?

### ISSUE THREAD

**Issue by Zxilly** [psastras/sarif-rs#646]
https://docs.rs/serde-sarif/latest/serde_sarif/#warning-very-unstable-early-implementation shows the lib was unstable.  But the source of this line was added three years ago.  Can this library be considered stable now?

**Comment by psastras** [comment]
@Zxilly I suppose so yes, I'll remove the warning signs. TBH I intended to revisit the API at some point and actually think about it (the initial implementation had no thought whatsoever behind it), but at this point as you say it hasn't changed for three years so I guess its stable in that sense.

**Comment by psastras** [comment]
this has been removed as of 0.5.0 https://docs.rs/serde-sarif/latest/serde_sarif/#warning-very-unstable-early-implementation
